spring.application.name=springboot-web
server.port=8000
#Se pueden declarar configuraciones externas es por esta razon que marca como propiedad desconocida 

#Se debe evitar caracteres especiales ya que puede presentar problemas 
